Use float literals for `TEST_FLTEQ`
When using the `TEST_FLTEQ` macro, pass float literals for the
comparision argument, to avoid errors of the form:

    error: absolute value function 'fabsf' given an argument of
    type 'double' but has parameter of type 'float' which may cause
    truncation of value [-Werror,-Wabsolute-value]